[package]
name = "discord-theme-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
angular-units = { version = "0.2.4", default-features = false }
prisma = { version = "0.1.1", default-features = false }
slint = "1.1.1"

[build-dependencies]
slint-build = "1.1.0"
